<a href="https://colab.research.google.com/github/MKoshi05/DataScientist-training/blob/main/%E2%91%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl


## インデックス参照

In [ ]:
sample_array = np.arange(10)
print("sample_array:",sample_array)

#前から数字を5つ取得して、sample_array_sliceに入れる
sample_array_slice = sample_array[0:5]
print("sample_array_slice:",sample_array_slice)



sample_array: [0 1 2 3 4 5 6 7 8 9]
sample_array_slice: [0 1 2 3 4]


In [ ]:
#sample_array_sliceの3文字目までを10で置換
sample_array_slice[0:3] = 10
print(sample_array_slice)

#スライスの変更は、元のリストにも反映される
print(sample_array)

"""
sample_array_sliceは、元データであるsample_arrayを「参照」しているだけ。
元データをコピーして格納しているわけではないので、sample_array_sliceを変更すること、元データを変更することに等しい
"""

[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


## データのコピー

In [ ]:
#元データを「参照」ではなく、コピーしたいときは、copyを用いる
sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20
print(sample_array_copy)

print("元のデータは変更されていない")
print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
元のデータは変更されていない
[10 10 10  3  4  5  6  7  8  9]


## ブールインデックス参照

In [ ]:
#データ準備
sample_names = np.array(["a","b","c","d","a"])
random.seed(0)
data = random.randn(5,5)

print(sample_names)
print(data)

#ブールインデックス参照を使って、要素を取り出す
sample_names =="a"

#この結果を条件として指定し、dataの要素を取り出す
#0番目と4番目がTrueなので、0行目と4行目の要素が取り出される
data[sample_names == "a"]

['a' 'b' 'c' 'd' 'a']
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]


array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462]])

## 条件制御

In [ ]:
"""
numpy.where(条件の配列,Xのデータ,Yのデータ)
XデータとYデータの２種類があるとき、条件を満たすかによってXもしくはYの要素を取り出すというように、取得するデータを切り分ける
"""
#条件制御のためのブールデータを作成
cond_data = np.array([True,True,False,False,True])

#Xデータの作成
x_array = np.array([1,2,3,4,5])

#Yデータの作成
y_array = np.array([100,200,300,400,500])

#条件制御実施
print(np.where(cond_data,x_array,y_array))
print("Trueの部分はXデータを取り出し、Falseの部分はYデータを取り出せた")

[  1   2 300 400   5]
Trueの部分はXデータを取り出し、Falseの部分はYデータを取り出せた


## Practice

In [ ]:
#練習問題5-1
sample_names = np.array(["a","b","c","d","a"])
random.seed(0)
data = random.rand(5,5)

print(data[sample_names == "b"])

[[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]]


In [ ]:
#練習問題5-2
#対象の文字列以外を抽出する場合、!= を使う
print(data[sample_names != "c"])

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]


In [ ]:
#練習問題5-3
random.seed(0)
x_array = random.rand(5)
y_array = random.rand(5)
print(x_array)
print(y_array)
#ブールインデックス参照と条件制御の組み合わせ
sample_names = np.array(["a","a","c","d","a"])
print(np.where(sample_names == "a",y_array,x_array))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
[0.64589411 0.43758721 0.60276338 0.54488318 0.38344152]


## Numpyの演算処理

In [ ]:
#重複の削除
cond_data = np.array([True,True,False,True])
print(cond_data)

print(np.unique(cond_data))

[ True  True False  True]
[False  True]


In [ ]:
#ユニバーサル関数
#すべての要素に対して、関数を適用するための関数

sample_data = np.arange(10)

print(sample_data)
print("すべての要素の平方根",np.sqrt(sample_data))
print("すべての要素のネイピア指数関数",np.exp(sample_data))

[0 1 2 3 4 5 6 7 8 9]
すべての要素の平方根 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
すべての要素のネイピア指数関数 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [ ]:
#最小値、最大値、平均、合計
sample_multi_data01 = np.arange(99).reshape(11,9)

print(sample_multi_data01)
print("最大値",np.max(sample_multi_data01))
print("最小値",sample_multi_data01.min())
print("平均値",np.mean(sample_multi_data01))
print("合計",sample_multi_data01.sum())

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98]]
最大値 98
最小値 0
平均値 49.0
合計 4851


In [ ]:
#真偽判定
print("少なくとも１つ以上Trueがあるかどうか",np.any(cond_data))
print("すべてTrueかどうか",cond_data.all())
print()
#条件を指定してからsumを指定すると、条件に合致する「要素の個数」を調べられる
print(sample_multi_data01)
print("サンプルデータのうち、平均値より大きい要素の個数",(sample_multi_data01>np.mean(sample_multi_data01)).sum())

少なくとも１つ以上Trueがあるかどうか True
すべてTrueかどうか False

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98]]
サンプルデータのうち、平均値より大きい要素の個数 49


In [ ]:
#対角成分の計算
sample_multi_data02 = np.arange(2,11).reshape(3,3)
print(sample_multi_data02)

#対角成分（diagonal component）の表示
print("対角成分",np.diag(sample_multi_data02))
#対角成分の和(Trace)の表示
print("対角成分の和",np.trace(sample_multi_data02))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
対角成分 [ 2  6 10]
対角成分の和 18


# Practice

In [ ]:
#練習問題5-4
#基本データを表示してください
sample_multi_prac = np.arange(16).reshape(4,4)
print(sample_multi_prac)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#練習問題5-5
#基本データの最大値、最小値、合計値、平均値を求めてください
print("最大値",np.max(sample_multi_prac))
print("最小値",sample_multi_prac.min())
print("合計値",np.sum(sample_multi_prac))
print("平均値",sample_multi_prac.mean())
print("標準偏差",np.std(sample_multi_prac))

最大値 15
最小値 0
合計値 120
平均値 7.5
標準偏差 4.6097722286464435


In [ ]:
#練習問題5-6
#基本データについて、対角成分の表示、対角成分の和を計算してください
print(sample_multi_prac)
print("対角成分の表示",np.diag(sample_multi_prac))
print("対角成分の和",np.trace(sample_multi_prac))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
対角成分の表示 [ 0  5 10 15]
対角成分の和 30


## 配列操作とブロードキャスト

行列の次元を変更したり、結合・分割を行う

In [ ]:
#再形成（行列の次元を変えること）
#基本データ
sample_data = np.arange(10)
print(sample_data)
print()
print("２行５列のデータ")
print(sample_data.reshape(2,5))

[0 1 2 3 4 5 6 7 8 9]

２行５列のデータ
[[0 1 2 3 4]
 [5 6 7 8 9]]


データの結合

In [ ]:
#データ準備
sample01 = np.arange(10).reshape(2,5)
sample02 = np.arange(3,13).reshape(2,5)
sample03 = np.arange(33,43).reshape(2,5)
#次元数は揃えておくことが必要
np.concatenate([sample01,sample02,sample03],axis=0)
#axis=0で行方向に結合
#vstackを使ってもできる（vertical方向に結合）

print("axis=1で列方向に結合")
np.concatenate([sample01,sample02,sample03],axis=1)
#hstackを使ってもできる（horizonal方向に結合）

axis=1で列方向に結合


array([[ 0,  1,  2,  3,  4,  3,  4,  5,  6,  7, 33, 34, 35, 36, 37],
       [ 5,  6,  7,  8,  9,  8,  9, 10, 11, 12, 38, 39, 40, 41, 42]])

配列の分割

In [ ]:
#splitを使って配列を分割する
vstac_data = np.vstack([sample01,sample02,sample03])
print(vstac_data)
print()
#vsatck_dataを３つに分割し、それぞれfirst,second,thirdという変数に格納
first,second,third = np.split(vstac_data,[2,4])
print(first)
print()
print(second)
print()
print(third)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [33 34 35 36 37]
 [38 39 40 41 42]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]

[[33 34 35 36 37]
 [38 39 40 41 42]]


繰り返し処理（repeat）

In [ ]:
#repeatを使うと、各要素が、指定した回数分だけ繰り返されて生成される。
print(first.repeat(100))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

ブロードキャスト

In [ ]:
#配列の大きさが異なっているときに、自動的に要素をコピーして、配列の大きさを揃える機能
sample_data = np.arange(10,20)
print(sample_data)
print(sample_data + 5)

[10 11 12 13 14 15 16 17 18 19]
[15 16 17 18 19 20 21 22 23 24]


# 練習問題

In [ ]:
#練習問題5-7、5-8
#２つの配列の結合
prac_data01 = np.arange(12).reshape(3,4)
prac_data02 = np.random.randn(12).reshape(3,4)
print("基本データ")
print(prac_data01)
print(prac_data02)

print()
print("縦方向に結合")
print(np.vstack([prac_data01,prac_data02]))
print()
print("横方向に結合")
print(np.hstack([prac_data01,prac_data02]))

基本データ
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.46513165  0.07010071  0.4261321  -1.74118461]
 [-0.52575523  1.32364117 -1.58371261 -0.4101099 ]
 [-1.73201129  1.25565905  0.78964701 -0.02435958]]

縦方向に結合
[[ 0.          1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.         10.         11.        ]
 [ 0.46513165  0.07010071  0.4261321  -1.74118461]
 [-0.52575523  1.32364117 -1.58371261 -0.4101099 ]
 [-1.73201129  1.25565905  0.78964701 -0.02435958]]

横方向に結合
[[ 0.          1.          2.          3.          0.46513165  0.07010071
   0.4261321  -1.74118461]
 [ 4.          5.          6.          7.         -0.52575523  1.32364117
  -1.58371261 -0.4101099 ]
 [ 8.          9.         10.         11.         -1.73201129  1.25565905
   0.78964701 -0.02435958]]


In [ ]:
#練習問題5-9
#サンプルデータの各要素に３を加える
sample_list = [1,2,3,4,5]
print(sample_list)
print(np.array(sample_list) + 3)

[1, 2, 3, 4, 5]
[4 5 6 7 8]
